name: "Set Environment Variables"
description: "Configures environment variables"
runs:
  using: "composite"
  steps:
    - run: |
        subscriptionName="Sandbox"

        EV1=$(echo "$(az group show -n blog -o tsv --query 'location')" | sed "s/\r//")
        echo "EV1=$EV1" >> $GITHUB_ENV
      shell: bash