name: 01-Deploy-Infrastructure

on: 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure login
        if: success()
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Azure CLI extensions to auto-install
        if: success()
        run: |
          az config set extension.use_dynamic_install=yes_without_prompt

      - name: Set Env Vars
        if: success()
        run: |
          EV1="foo"
          echo "EV1=$EV1" >> $GITHUB_ENV

      - name: Run Script
        if: success()
        run: |
          chmod +x ./scripts/test.sh
          ./scripts/test.sh

      - name: Azure logout
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az logout
            az cache purge
            az account clear

