name: 01-Deploy-Infrastructure

on: 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure login
        if: success()
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Azure CLI extensions to auto-install
        if: success()
        run: |
          az config set extension.use_dynamic_install=yes_without_prompt

      - name: Set Environment Variables
        if: success()
        run: |
          chmod +x ./scripts/set-env-vars.sh
          ./scripts/set-env-vars.sh

      - name: Create Resource Groups
        if: success()
        run: |
          chmod +x ./scripts/01-deploy-infra/01-deploy-rgs.sh
          ./scripts/01-deploy-infra/01-deploy-rgs.sh

      - name: Deploy User-Assigned MI
        if: success()
        run: |
          chmod +x ./scripts/01-deploy-infra/02-deploy-uami.sh
          ./scripts/01-deploy-infra/02-deploy-uami.sh

      - name: Deploy Network
        if: success()
        run: |
          chmod +x ./scripts/01-deploy-infra/03-deploy-network.sh
          ./scripts/01-deploy-infra/03-deploy-network.sh

      - name: Deploy Azure Compute Gallery
        if: success()
        run: |
          chmod +x ./scripts/01-deploy-infra/04-deploy-compute-gallery.sh
          ./scripts/01-deploy-infra/04-deploy-compute-gallery.sh

      - name: Azure logout
        if: always()
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az logout
            az cache purge
            az account clear
