name: 01-Deploy-Infrastructure

on: 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Environment Variables
        if: success()
        run: |
          chmod +x ./scripts/test.sh
          ./scripts/test.sh

      - name: Get Environment Variables
        if: success()
        run: |
          echo $FOO
          echo ${{ env.FOO }}
