name: Deploy-Infra

on: 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure login
        if: success()
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Azure CLI extensions
        if: success()
        run: |
          az config set extension.use_dynamic_install=yes_without_prompt

      - name: Debug
        if: success()
        run: |
          sudo apt install jq -y
          subId=$(echo "${{ secrets.AZURE_CREDENTIALS }}" | jq -r '.subscriptionId')
          echo $subId

      - name: Azure logout
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az logout
            az cache purge
            az account clear

