name: 02-Create-Source-Images

on: 
  workflow_dispatch:

jobs:
  create_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure login
        if: success()
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Azure CLI extensions to auto-install
        if: success()
        run: |
          az config set extension.use_dynamic_install=yes_without_prompt

      - name: Set Environment Variables
        if: success()
        run: |
          chmod +x ./scripts/set-env-vars.sh
          ./scripts/set-env-vars.sh

      - name: Prepare VMs for Capture
        if: success()
        run: |
          chmod +x ./scripts/02-create-source-images/06-prepare-vms-for-capture.sh
          ./scripts/02-create-source-images/06-prepare-vms-for-capture.sh


      - name: Azure logout
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az logout
            az cache purge
            az account clear
