name: 02-Create-Source-Images

on: 
  workflow_dispatch:

jobs:
  create_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure login
        if: success()
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Azure CLI extensions to auto-install
        if: success()
        run: |
          az config set extension.use_dynamic_install=yes_without_prompt

      - name: Set Environment Variables
        if: success()
        run: |
          chmod +x ./scripts/set-env-vars.sh
          ./scripts/set-env-vars.sh

      - name: Create Resource Groups
        if: success()
        run: |
          chmod +x ./scripts/02-create-source-images/01-deploy-rgs.sh
          ./scripts/02-create-source-images/01-deploy-rgs.sh

      - name: Prepare SSH keys
        if: success()
        run: |
          chmod +x ./scripts/02-create-source-images/02-prepare-ssh.sh
          ./scripts/02-create-source-images/02-prepare-ssh.sh

      - name: Create Gallery Image Definitions
        if: success()
        run: |
          chmod +x ./scripts/02-create-source-images/03-create-image-definitions.sh
          ./scripts/02-create-source-images/03-create-image-definitions.sh

      - name: Deploy Source VMs
        if: success()
        run: |
          chmod +x ./scripts/02-create-source-images/04-deploy-source-vms.sh
          ./scripts/02-create-source-images/04-deploy-source-vms.sh

      - name: Allow GH Runner SSH Access
        if: success()
        run: |
          chmod +x ./scripts/02-create-source-images/05-allow-gh-runner-ssh.sh
          ./scripts/02-create-source-images/05-allow-gh-runner-ssh.sh

      - name: Create Admin User on Source VMs
        if: success()
        run: |
          chmod +x ./scripts/02-create-source-images/06a-create-admin-user-with-azure-cli.sh
          ./scripts/02-create-source-images/06a-create-admin-user-with-azure-cli.sh


      - name: Prepare VMs for Capture
        if: success()
        run: |
          chmod +x ./scripts/02-create-source-images/07-prepare-vms-for-capture.sh
          ./scripts/02-create-source-images/07-prepare-vms-for-capture.sh


      - name: Azure logout
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az logout
            az cache purge
            az account clear
