name: Set Environment Variables

on:
  workflow_call:
    secrets:
      AZURE_CREDENTIALS:
        required: true

jobs:
  set-env-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        if: success()
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Environment Variables
        if: success()
        run: |
          EV1="foo2"
          echo "EV1=$EV1" >> $GITHUB_ENV

      - name: Azure logout
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az logout
            az cache purge
            az account clear
