name: Set Environment Variables

on:
  workflow_call:
    secrets:
      AZURE_CREDENTIALS:
        required: true

jobs:
  set-env-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Azure CLI extensions to auto-install
        if: success()
        run: |
          az config set extension.use_dynamic_install=yes_without_prompt

      - name: Set Environment Variables
        if: success()
        run: |
          EV1="foo2"
          echo "EV1=$EV1" >> $GITHUB_ENV

      - name: Azure logout
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az logout
            az cache purge
            az account clear
